version: "3.7"
services:
#TAKY COT
   taky-cot:
    image: skadakar/taky:latest
    container_name: taky-cot
    user: "1000"
    network_mode: host
    restart: unless-stopped
    environment:
      - mode=cot
    volumes:
      - /root/taky-data/:/data
#TAKY DATA
   taky-data:
    depends_on:
      - taky-cot
    image: skadakar/taky:latest
    container_name: taky-data
    user: "1000"
    network_mode: host
    restart: unless-stopped
    environment:
      - mode=data
    volumes:
      - /root/taky-data/:/data
      
