version: "0.2"
services:
  taky-cot:
    image: skadakar/taky:unified
    container_name: taky-cot
    user: "1000"
    restart: unless-stopped
    environment:
     - mode=cot
     - public_ip=123.123.123.123
    volumes:
      - /root/data/:/data
  taky-data:
    image: skadakar/taky:unified
    container_name: taky-data
    user: "1000"
    restart: unless-stopped
    environment:
     - mode=data
     - public_ip=123.123.123.123
    volumes:
      - /root/data/:/data
volumes:
        data:
