name: Latest build
# Controls when the workflow will run
on:
  schedule:
    - cron: "0 1 * * *"
  # Triggers the workflow on push or pull request events but only for the main branch
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: checkout code
        uses: actions/checkout@v3

      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v2
        with:
          platforms: all
      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v2
        with:
          version: latest
      -
        name: Available platforms
        run: echo ${{ steps.buildx.outputs.platforms }}
      - name: build the image
        run: |
          docker buildx build -f Dockerfile.latest \
          --tag skadakar/taky:latest \
          --platform linux/amd64,linux/arm64 . --push
